s=input()
while(s!=""):
    if(s.startswith("144")):
        s=s[3:]
    elif(s.startswith("14")):
        s=s[2:]
    elif(s.startswith("1")):
        s=s[1:]
    else:
        print("NO")
        break
if(s==""):
    print("YES")